generate segment for channel: 1
working on 0 sections
0it [00:00, ?it/s]0it [00:00, ?it/s]generate segment for channel: 3
working on 182 sections

python: can't open file 'parallel': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "segment_tifs.py", line 1, in <module>
    from lib.TiffSegmentor import TiffSegmentor
ImportError: No module named lib.TiffSegmentor
generate segment for channel: 1
working on 438 sections
generate segment for channel: 1
working on 438 sections
Traceback (most recent call last):
  File "segment_tifs.py", line 13, in <module>
    segmentor.generate_tiff_segments(channel = 1,create_csv = False)
  File "/data/programming/preprocessing-pipeline/src/lib/TiffSegmentor.py", line 71, in generate_tiff_segments
    for _ in tqdm.tqdm(p.map(workernoshell, commands), total=len(commands)):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 765, in get
    self.wait(timeout)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 762, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
generate segment for channel: 1
working on 438 sections
generate segment for channel: 1
working on 0 sections
0it [00:00, ?it/s]0it [00:00, ?it/s]generate segment for channel: 3
working on 162 sections

  0%|          | 0/162 [00:00<?, ?it/s]100%|██████████| 162/162 [00:00<00:00, 318704.15it/s]
generate segment for channel: 1
working on 0 sections
0it [00:00, ?it/s]0it [00:00, ?it/s]generate segment for channel: 3
working on 384 sections

  0%|          | 0/384 [00:00<?, ?it/s]100%|██████████| 384/384 [00:00<00:00, 446895.88it/s]
